# Generated by Django 6.0.2 on 2026-02-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='full_name',
        ),
    ]
