# Generated by Django 6.0.2 on 2026-02-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_appointments_appointment_date_doctor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(blank=True, editable=False, unique=True),
        ),
    ]
